import { useTranslations } from "next-intl";

export const useGetCurrencies = () => {
  const t = useTranslations("Currencies");

  const currencies = [
    { code: "AED", name: t("AED") },
    { code: "AFN", name: t("AFN") },
    { code: "ALL", name: t("ALL") },
    { code: "AMD", name: t("AMD") },
    { code: "ANG", name: t("ANG") },
    { code: "AOA", name: t("AOA") },
    { code: "ARS", name: t("ARS") },
    { code: "AUD", name: t("AUD") },
    { code: "AWG", name: t("AWG") },
    { code: "AZN", name: t("AZN") },
    { code: "BAM", name: t("BAM") },
    { code: "BBD", name: t("BBD") },
    { code: "BDT", name: t("BDT") },
    { code: "BGN", name: t("BGN") },
    { code: "BHD", name: t("BHD") },
    { code: "BIF", name: t("BIF") },
    { code: "BMD", name: t("BMD") },
    { code: "BND", name: t("BND") },
    { code: "BOB", name: t("BOB") },
    { code: "BRL", name: t("BRL") },
    { code: "BSD", name: t("BSD") },
    { code: "BTN", name: t("BTN") },
    { code: "BWP", name: t("BWP") },
    { code: "BYN", name: t("BYN") },
    { code: "BZD", name: t("BZD") },
    { code: "CAD", name: t("CAD") },
    { code: "CDF", name: t("CDF") },
    { code: "CHF", name: t("CHF") },
    { code: "CLP", name: t("CLP") },
    { code: "CNY", name: t("CNY") },
    { code: "COP", name: t("COP") },
    { code: "CRC", name: t("CRC") },
    { code: "CUP", name: t("CUP") },
    { code: "CVE", name: t("CVE") },
    { code: "CZK", name: t("CZK") },
    { code: "DJF", name: t("DJF") },
    { code: "DKK", name: t("DKK") },
    { code: "DOP", name: t("DOP") },
    { code: "DZD", name: t("DZD") },
    { code: "EGP", name: t("EGP") },
    { code: "ERN", name: t("ERN") },
    { code: "ETB", name: t("ETB") },
    { code: "EUR", name: t("EUR") },
    { code: "FJD", name: t("FJD") },
    { code: "FKP", name: t("FKP") },
    { code: "FOK", name: t("FOK") },
    { code: "GBP", name: t("GBP") },
    { code: "GEL", name: t("GEL") },
    { code: "GGP", name: t("GGP") },
    { code: "GHS", name: t("GHS") },
    { code: "GIP", name: t("GIP") },
    { code: "GMD", name: t("GMD") },
    { code: "GNF", name: t("GNF") },
    { code: "GTQ", name: t("GTQ") },
    { code: "GYD", name: t("GYD") },
    { code: "HKD", name: t("HKD") },
    { code: "HNL", name: t("HNL") },
    { code: "HRK", name: t("HRK") },
    { code: "HTG", name: t("HTG") },
    { code: "HUF", name: t("HUF") },
    { code: "IDR", name: t("IDR") },
    { code: "ILS", name: t("ILS") },
    { code: "IMP", name: t("IMP") },
    { code: "INR", name: t("INR") },
    { code: "IQD", name: t("IQD") },
    { code: "IRR", name: t("IRR") },
    { code: "ISK", name: t("ISK") },
    { code: "NOK", name: t("NOK") },
    { code: "PLN", name: t("PLN") },
    { code: "RON", name: t("RON") },
    { code: "RSD", name: t("RSD") },
    { code: "RUB", name: t("RUB") },
    { code: "SEK", name: t("SEK") },
    { code: "UAH", name: t("UAH") },
    { code: "USD", name: t("USD") },
  ];

  return currencies;
};
